spring:
  application:
    name: homecare

  datasource:
    url: jdbc:mysql://localhost:3306/homecare
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.MySQL8Dialect
